name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy-documentation:
    name: Deploy documentation in html format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build . -t aprendepython
      - name: Build documentation in html
        run: docker run --rm -v .:/code aprendepython
      - name: Fix theme
        run: perl -pi -e 's/document.body.dataset.theme = .*/document.body.dataset.theme = "light”;/' $(find _build/dirhtml -name '*.html')
      - name: Sync files with production server
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: _build/
          remote_host: aprendepython.es
          remote_path: ${{ secrets.REMOTE_BUILD_PATH }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}
